spring.application.name=TechLingo Backend
server.port=8080

spring.mongodb.uri=mongodb+srv://Cluster69797:XF1qRFBUTXtg@cluster69797.g6e9wae.mongodb.net/techlingo

jwt.secret=myVeryStrongSecretKeyForTechLingoJwtAuthentication12345
jwt.expiration=86400000